// <auto-generated />
using API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Migrations
{
    [DbContext(typeof(ClimateDetailContext))]
    [Migration("20201222094556_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("API.Models.ClimateDetail", b =>
                {
                    b.Property<int>("ClimateDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClimateName")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<int>("GlobalRadiation")
                        .HasColumnType("int(3)");

                    b.Property<int>("InCoefficient")
                        .HasColumnType("int(3)");

                    b.Property<int>("InTemp")
                        .HasColumnType("int(2)");

                    b.Property<int>("OutCoefficient")
                        .HasColumnType("int(3)");

                    b.Property<int>("OutTemp")
                        .HasColumnType("int(2)");

                    b.HasKey("ClimateDetailId");

                    b.ToTable("ClimateDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
